### ISSUE TITLE
Re-add ability to rebuild

### ISSUE THREAD

**Issue by holmesb** [terraform-coop/terraform-provider-foreman#130]
[Discussion](https://github.com/terraform-coop/terraform-provider-foreman/discussions/125) resulted in agreement to reintroduce the ability to rebuild. This was [removed](https://github.com/terraform-coop/terraform-provider-foreman/pull/122) in v6. New `foreman_host` argument `set_build_flag` will default to false. This will still allow the Foreman default behaviour of initially building new hosts, but will avoid the previous incarnation's (`build`) risk of accidental rebuilds after next Terraform run. Expectation of new behaviour vs current:

- Now (v6): no `set_build_flag` argument exists, initial creation of `foreman_host` results in it being built, since this is the Foreman default. Re-running Terraform does not rebuild.
- New: `set_build_flag = false` (default): This provider does not tell Foreman API to disable the build flag. Instead, due to the fact Foreman defaults to build = true, initial creation of `foreman_host` in Terraform still results in host being built. Re-running of Terraform will not rebuild.
- New: `set_build_flag = true`: Initial creation of `foreman_host` results in it being built. Re-run of Terraform will rebuild. Changing back to false will prevent rebuild.

**Comment by bitkeks** [comment]
> Re-run of Terraform will rebuild. Changing back to false will prevent rebuild

Please note that setting the `set_build_flag` argument in TF to `true` does not automatically re-install the host through Foreman. The flag will have an effect after the next reboot of the machine, because Foreman will then trigger the installation process again.
