### ISSUE TITLE
Please add a ressource to create (composite) content views

### ISSUE THREAD

**Issue by bigon** [terraform-coop/terraform-provider-foreman#140]
Hello,

AFAICS, there is no resource in the module to create (composite) content views.

Would be nice if there was such thing

**Comment by lhw** [comment]
Closed by #150

**Comment by bitkeks** [comment]
We are currently working on fixes for CVs and CCVs. These resources are more complicated than anticipated. Please test as far as you can and provide feedback. That would help us immensely!

See https://github.com/terraform-coop/terraform-provider-foreman/pull/157
