### ISSUE TITLE
Please add a ressource to create katello lifecycle environments

### ISSUE THREAD

**Issue by bigon** [terraform-coop/terraform-provider-foreman#141]
Hello,

Again AFAICS, there is no resource to create/update lifecycle environments

Would be nice to have that

**Comment by bitkeks** [comment]
Hi, PR #149 implements Katello lifecycle environments.

I added a tutorial on how to build the provider from source, in case you have the possibilities to test it: https://github.com/terraform-coop/terraform-provider-foreman/wiki/Development#build-the-provider-from-source-code
