### ISSUE TITLE
Support Darwin arm64

### ISSUE THREAD

**Issue by evgenkisel** [terraform-coop/terraform-provider-foreman#154]
Hello,

I'd like to use the plugin in my TF, but it doesn't work as I use Apple M1 laptop to run my TF code.

`Error: Incompatible provider version
Provider registry.terraform.io/terraform-coop/foreman v0.6.2 does not have a package available for your current platform, darwin_arm64. Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.`

Darwin support was disabled in the release v0.3.2 like 3 years ago. I forked the repo and tried to build the project with enabled Darwin support, and it works without any issue. What was that issue? Probably it's possible to return Darwin to `.goreleaser.yml`

I can create a PR for this if everything is good.

Appreciate for any help or feedback!

**Comment by lhw** [comment]
At the time the issue were some very weird complications with the test suite. A lot of times the tests were randomly failing on darwin, and only on darwin.
I am totally fine with re-enabling it. Go has come a long way in the last few years.
