### ISSUE TITLE
missing settings module

### ISSUE THREAD

**Issue by vhsantos** [terraform-coop/terraform-provider-foreman#166]
The settings module (Administer > Settings) are missing and it is not possible to setup or query any of the parameters from there (smtp, default user. 
This (IMHO), should be very similar to the [foreman_global_parameter](https://registry.terraform.io/providers/terraform-coop/foreman/latest/docs/resources/foreman_global_parameter)

**Comment by bitkeks** [comment]
It is implemented as a data source: [/examples/setting/main.tf](https://github.com/terraform-coop/terraform-provider-foreman/blob/300dee26b19a8ad752269e690b153466c9e2000d/examples/setting/main.tf). No idea why the docs vanished.
