### ISSUE TITLE
missing parameter value on the repository

### ISSUE THREAD

**Issue by vhsantos** [terraform-coop/terraform-provider-foreman#170]
On /foreman_katello_repository code
https://github.com/terraform-coop/terraform-provider-foreman/blob/27ca840eef52bcf8355fa458ac6d5325e8c04b16/foreman/resource_foreman_katello_repositories.go#L192-L201

there is the mirroring_policy option, but it only accept two **parameters additive** and **mirror_content_only**, nevertheless, the **mirror_complete** value is missing. 

Additional to it, the mirroring_policy aren't commented on the documentation neither !! :-(

**Comment by bitkeks** [comment]
Will be fixed by approved PR #174
