### ISSUE TITLE
partition table missing default parameter

### ISSUE THREAD

**Issue by vhsantos** [terraform-coop/terraform-provider-foreman#172]
[partitiontable](https://registry.terraform.io/providers/terraform-coop/foreman/latest/docs/data-sources/foreman_partitiontable) don't contain the parameter default (Default templates are automatically added to new organizations and locations).

**Comment by bitkeks** [comment]
We'd need this field in https://apidocs.theforeman.org/katello/latest/apidoc/v2/ptables/create.html - but it's not there. This does not seem to be available through the API, even if it's visible in the GUI.
