### ISSUE TITLE
foreman host_collection resource

### ISSUE THREAD

**Issue by vhsantos** [terraform-coop/terraform-provider-foreman#176]
Hello there,

Are in the TODO list the option to include the foreman host_collections ?? 
https://theforeman.org/plugins/katello/4.13/api/apidoc/v2/host_collections.html

**Comment by bitkeks** [comment]
Not at the moment. We are focussing on stabilizing what is already there, fixing bugs and releasing 0.7.0 as soon as possible. Maybe after that new API resources will be considered.

Reference link: https://apidocs.theforeman.org/katello/latest/apidoc/v2/host_collections.html
