### ISSUE TITLE
Deployment of Github pages fails: not found deploy key or tokens

### ISSUE THREAD

**Issue by bitkeks** [terraform-coop/terraform-provider-foreman#182]
Currently, the docs deployment to/from branch `gh-pages` fails with error `Action failed with "not found deploy key or tokens"`

Example: https://github.com/terraform-coop/terraform-provider-foreman/actions/runs/10492532276/job/29064295918

Maybe an upgrade to `peaceiris/actions-gh-pages@v4` and using the `GITHUB_TOKEN` method will solve the problem? See https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#readme

**Comment by lhw** [comment]
I will check on this as soon as I am on my laptop. Seems odd. The token was set to not expire.

**Comment by bitkeks** [comment]
@lhw any new update?
