### ISSUE TITLE
foreman_katello_product is broken

### ISSUE THREAD

**Issue by agriffit79** [terraform-coop/terraform-provider-foreman#54]
It seems recent versions of Katello have made `organization_id` a required parameter. The provider needs to be updated to handle this.

[GET /katello/api/products](https://theforeman.org/plugins/katello/3.17/api/apidoc/v2/products/index.html)

I've started investigating this. I'm thinking to use the ID in the provider config rather than make it an explicit parameter of the resource.

**Comment by lhw** [comment]
Lovely. Another version of the API call which doesn't match the same paradigm they already used elsewhere. The Foreman API might be one of the worst, or at least most inconsistent ones I have ever seen

**Comment by bitkeks** [comment]
Fixed in bc544ceddb86f143bf72d14929419623d2811812, merged via PR #142
