### ISSUE TITLE
Old versions under HanseMerkur/terraform-provider-foreman are currently not working correctly.

### ISSUE THREAD

**Issue by lhw** [terraform-coop/terraform-provider-foreman#84]
Due to the migration of the repository the current release links in the terraform registry broke. I already contacted the terraform support regarding the indexing issue.

**Comment by togoschi** [comment]
@lhw is there any way to bypass the current issue?

got this when trying to install v0.5.1

```
Error: Failed to install provider
│ 
│ Error while installing hansemerkur/foreman v0.5.1: checksum list has
│ unexpected SHA-256 hash
│ 2432fd8c72cbf867ac8be7f540e1d5f7412e244222c6c3b46dc98bc148ae0ff7 (expected
│ 9990cd41b59af84c53ff671e55f20bfdada7d92946b45a58bc949dd95a97ba96)

```
and this when trying to install v0.5.2

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hansemerkur/foreman v0.5.2: could not query provider
│ registry for registry.terraform.io/hansemerkur/foreman: failed to retrieve
│ authentication checksums for provider: 404 Not Found
╵
```
Installing an older version like v0.4.5 is still working

**Comment by lhw** [comment]
I basically can't do anything right now. v0.5.1 apparently has the wrong checksum as can be seen in the error message. I deleted 0.5.2 as it also had a wrong checksum but 0.5.3 with the correct checksum is not being detected by the registry. The ticket is open with HashiCorp but hasn't moved in five days. But I guess thats expected with them if you don't pay.
