### ISSUE TITLE
Power operation fails

### ISSUE THREAD

**Issue by mgusek-interhyp** [terraform-coop/terraform-provider-foreman#93]
Hi,
if you only want to create a host and set build-Flag to true and you have no compute resources, power operation fails with "Power operations are not enabled on this host". I can remember we talked about that problem, but i did'nt find the issue on https://github.com/HanseMerkur/terraform-provider-foreman. I think we wanted to add a flag, running power operations or not and i'm pretty sure, there was a PR. Can you please have a look ?

Michael

**Comment by lhw** [comment]
I'm guessing thats closed by your PR. If not re-open it as you please.
